# 天气预报数据模块配置 (pure torch)
_target_: src.datamodules.forecast.state_datamodule.StateForecastDataModule

root_dir: ${paths.era5_lr_dir}

# 气象变量
variables: [
  "t2m", "u10", "v10", "msl",
  "z-50", "z-100", "z-150", "z-200", "z-250", "z-300", "z-400", "z-500", "z-600", "z-700", "z-850", "z-925", "z-1000",
  "u-50", "u-100", "u-150", "u-200", "u-250", "u-300", "u-400", "u-500", "u-600", "u-700", "u-850", "u-925", "u-1000",
  "v-50", "v-100", "v-150", "v-200", "v-250", "v-300", "v-400", "v-500", "v-600", "v-700", "v-850", "v-925", "v-1000",
  "t-50", "t-100", "t-150", "t-200", "t-250", "t-300", "t-400", "t-500", "t-600", "t-700", "t-850", "t-925", "t-1000",
  "q-50", "q-100", "q-150", "q-200", "q-250", "q-300", "q-400", "q-500", "q-600", "q-700", "q-850", "q-925", "q-1000",
]

# 数据集划分
start_train_year: 2010
start_val_year: 2022
start_test_year: 2023
end_year: 2024

# 预报参数
max_lead_time: 24
iter_num: 1

# 训练参数
seed: 1024
batch_size: 48
num_workers: 8
shuffle: true
pin_memory: true
prefetch_factor: 2

# debug mode
debug: false